-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Mem2Stream_Batch10 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    m_axi_in_V_AWVALID : OUT STD_LOGIC;
    m_axi_in_V_AWREADY : IN STD_LOGIC;
    m_axi_in_V_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_in_V_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_in_V_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_in_V_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_in_V_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_in_V_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_in_V_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_in_V_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_in_V_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_in_V_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_in_V_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_in_V_WVALID : OUT STD_LOGIC;
    m_axi_in_V_WREADY : IN STD_LOGIC;
    m_axi_in_V_WDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_in_V_WSTRB : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_in_V_WLAST : OUT STD_LOGIC;
    m_axi_in_V_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_in_V_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_in_V_ARVALID : OUT STD_LOGIC;
    m_axi_in_V_ARREADY : IN STD_LOGIC;
    m_axi_in_V_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_in_V_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_in_V_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_in_V_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_in_V_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_in_V_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_in_V_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_in_V_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_in_V_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_in_V_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_in_V_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_in_V_RVALID : IN STD_LOGIC;
    m_axi_in_V_RREADY : OUT STD_LOGIC;
    m_axi_in_V_RDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    m_axi_in_V_RLAST : IN STD_LOGIC;
    m_axi_in_V_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_in_V_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_in_V_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_in_V_BVALID : IN STD_LOGIC;
    m_axi_in_V_BREADY : OUT STD_LOGIC;
    m_axi_in_V_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_in_V_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_in_V_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    in_V_offset : IN STD_LOGIC_VECTOR (60 downto 0);
    inter0_V_V_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    inter0_V_V_full_n : IN STD_LOGIC;
    inter0_V_V_write : OUT STD_LOGIC;
    out_V_offset : IN STD_LOGIC_VECTOR (60 downto 0);
    out_V_offset_out_din : OUT STD_LOGIC_VECTOR (60 downto 0);
    out_V_offset_out_full_n : IN STD_LOGIC;
    out_V_offset_out_write : OUT STD_LOGIC );
end;


architecture behav of Mem2Stream_Batch10 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal out_V_offset_out_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_block_state1 : BOOLEAN;
    signal grp_Mem2Stream_fu_58_ap_start : STD_LOGIC;
    signal grp_Mem2Stream_fu_58_ap_done : STD_LOGIC;
    signal grp_Mem2Stream_fu_58_ap_idle : STD_LOGIC;
    signal grp_Mem2Stream_fu_58_ap_ready : STD_LOGIC;
    signal grp_Mem2Stream_fu_58_m_axi_in_V_AWVALID : STD_LOGIC;
    signal grp_Mem2Stream_fu_58_m_axi_in_V_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_Mem2Stream_fu_58_m_axi_in_V_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_Mem2Stream_fu_58_m_axi_in_V_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_Mem2Stream_fu_58_m_axi_in_V_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_Mem2Stream_fu_58_m_axi_in_V_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_Mem2Stream_fu_58_m_axi_in_V_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_Mem2Stream_fu_58_m_axi_in_V_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Mem2Stream_fu_58_m_axi_in_V_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_Mem2Stream_fu_58_m_axi_in_V_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Mem2Stream_fu_58_m_axi_in_V_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Mem2Stream_fu_58_m_axi_in_V_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_Mem2Stream_fu_58_m_axi_in_V_WVALID : STD_LOGIC;
    signal grp_Mem2Stream_fu_58_m_axi_in_V_WDATA : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_Mem2Stream_fu_58_m_axi_in_V_WSTRB : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Mem2Stream_fu_58_m_axi_in_V_WLAST : STD_LOGIC;
    signal grp_Mem2Stream_fu_58_m_axi_in_V_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_Mem2Stream_fu_58_m_axi_in_V_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_Mem2Stream_fu_58_m_axi_in_V_ARVALID : STD_LOGIC;
    signal grp_Mem2Stream_fu_58_m_axi_in_V_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_Mem2Stream_fu_58_m_axi_in_V_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_Mem2Stream_fu_58_m_axi_in_V_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_Mem2Stream_fu_58_m_axi_in_V_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_Mem2Stream_fu_58_m_axi_in_V_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_Mem2Stream_fu_58_m_axi_in_V_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_Mem2Stream_fu_58_m_axi_in_V_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Mem2Stream_fu_58_m_axi_in_V_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_Mem2Stream_fu_58_m_axi_in_V_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Mem2Stream_fu_58_m_axi_in_V_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Mem2Stream_fu_58_m_axi_in_V_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_Mem2Stream_fu_58_m_axi_in_V_RREADY : STD_LOGIC;
    signal grp_Mem2Stream_fu_58_m_axi_in_V_BREADY : STD_LOGIC;
    signal grp_Mem2Stream_fu_58_out_V_V_din : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_Mem2Stream_fu_58_out_V_V_write : STD_LOGIC;
    signal grp_Mem2Stream_fu_58_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call12 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);

    component Mem2Stream IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_in_V_AWVALID : OUT STD_LOGIC;
        m_axi_in_V_AWREADY : IN STD_LOGIC;
        m_axi_in_V_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_in_V_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_in_V_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_in_V_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_in_V_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_in_V_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_in_V_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_in_V_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_in_V_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_in_V_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_in_V_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_in_V_WVALID : OUT STD_LOGIC;
        m_axi_in_V_WREADY : IN STD_LOGIC;
        m_axi_in_V_WDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_in_V_WSTRB : OUT STD_LOGIC_VECTOR (7 downto 0);
        m_axi_in_V_WLAST : OUT STD_LOGIC;
        m_axi_in_V_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_in_V_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_in_V_ARVALID : OUT STD_LOGIC;
        m_axi_in_V_ARREADY : IN STD_LOGIC;
        m_axi_in_V_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_in_V_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_in_V_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_in_V_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_in_V_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_in_V_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_in_V_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_in_V_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_in_V_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_in_V_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_in_V_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_in_V_RVALID : IN STD_LOGIC;
        m_axi_in_V_RREADY : OUT STD_LOGIC;
        m_axi_in_V_RDATA : IN STD_LOGIC_VECTOR (63 downto 0);
        m_axi_in_V_RLAST : IN STD_LOGIC;
        m_axi_in_V_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_in_V_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_in_V_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_in_V_BVALID : IN STD_LOGIC;
        m_axi_in_V_BREADY : OUT STD_LOGIC;
        m_axi_in_V_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_in_V_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_in_V_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        in_V_offset : IN STD_LOGIC_VECTOR (60 downto 0);
        out_V_V_din : OUT STD_LOGIC_VECTOR (63 downto 0);
        out_V_V_full_n : IN STD_LOGIC;
        out_V_V_write : OUT STD_LOGIC );
    end component;



begin
    grp_Mem2Stream_fu_58 : component Mem2Stream
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_Mem2Stream_fu_58_ap_start,
        ap_done => grp_Mem2Stream_fu_58_ap_done,
        ap_idle => grp_Mem2Stream_fu_58_ap_idle,
        ap_ready => grp_Mem2Stream_fu_58_ap_ready,
        m_axi_in_V_AWVALID => grp_Mem2Stream_fu_58_m_axi_in_V_AWVALID,
        m_axi_in_V_AWREADY => ap_const_logic_0,
        m_axi_in_V_AWADDR => grp_Mem2Stream_fu_58_m_axi_in_V_AWADDR,
        m_axi_in_V_AWID => grp_Mem2Stream_fu_58_m_axi_in_V_AWID,
        m_axi_in_V_AWLEN => grp_Mem2Stream_fu_58_m_axi_in_V_AWLEN,
        m_axi_in_V_AWSIZE => grp_Mem2Stream_fu_58_m_axi_in_V_AWSIZE,
        m_axi_in_V_AWBURST => grp_Mem2Stream_fu_58_m_axi_in_V_AWBURST,
        m_axi_in_V_AWLOCK => grp_Mem2Stream_fu_58_m_axi_in_V_AWLOCK,
        m_axi_in_V_AWCACHE => grp_Mem2Stream_fu_58_m_axi_in_V_AWCACHE,
        m_axi_in_V_AWPROT => grp_Mem2Stream_fu_58_m_axi_in_V_AWPROT,
        m_axi_in_V_AWQOS => grp_Mem2Stream_fu_58_m_axi_in_V_AWQOS,
        m_axi_in_V_AWREGION => grp_Mem2Stream_fu_58_m_axi_in_V_AWREGION,
        m_axi_in_V_AWUSER => grp_Mem2Stream_fu_58_m_axi_in_V_AWUSER,
        m_axi_in_V_WVALID => grp_Mem2Stream_fu_58_m_axi_in_V_WVALID,
        m_axi_in_V_WREADY => ap_const_logic_0,
        m_axi_in_V_WDATA => grp_Mem2Stream_fu_58_m_axi_in_V_WDATA,
        m_axi_in_V_WSTRB => grp_Mem2Stream_fu_58_m_axi_in_V_WSTRB,
        m_axi_in_V_WLAST => grp_Mem2Stream_fu_58_m_axi_in_V_WLAST,
        m_axi_in_V_WID => grp_Mem2Stream_fu_58_m_axi_in_V_WID,
        m_axi_in_V_WUSER => grp_Mem2Stream_fu_58_m_axi_in_V_WUSER,
        m_axi_in_V_ARVALID => grp_Mem2Stream_fu_58_m_axi_in_V_ARVALID,
        m_axi_in_V_ARREADY => m_axi_in_V_ARREADY,
        m_axi_in_V_ARADDR => grp_Mem2Stream_fu_58_m_axi_in_V_ARADDR,
        m_axi_in_V_ARID => grp_Mem2Stream_fu_58_m_axi_in_V_ARID,
        m_axi_in_V_ARLEN => grp_Mem2Stream_fu_58_m_axi_in_V_ARLEN,
        m_axi_in_V_ARSIZE => grp_Mem2Stream_fu_58_m_axi_in_V_ARSIZE,
        m_axi_in_V_ARBURST => grp_Mem2Stream_fu_58_m_axi_in_V_ARBURST,
        m_axi_in_V_ARLOCK => grp_Mem2Stream_fu_58_m_axi_in_V_ARLOCK,
        m_axi_in_V_ARCACHE => grp_Mem2Stream_fu_58_m_axi_in_V_ARCACHE,
        m_axi_in_V_ARPROT => grp_Mem2Stream_fu_58_m_axi_in_V_ARPROT,
        m_axi_in_V_ARQOS => grp_Mem2Stream_fu_58_m_axi_in_V_ARQOS,
        m_axi_in_V_ARREGION => grp_Mem2Stream_fu_58_m_axi_in_V_ARREGION,
        m_axi_in_V_ARUSER => grp_Mem2Stream_fu_58_m_axi_in_V_ARUSER,
        m_axi_in_V_RVALID => m_axi_in_V_RVALID,
        m_axi_in_V_RREADY => grp_Mem2Stream_fu_58_m_axi_in_V_RREADY,
        m_axi_in_V_RDATA => m_axi_in_V_RDATA,
        m_axi_in_V_RLAST => m_axi_in_V_RLAST,
        m_axi_in_V_RID => m_axi_in_V_RID,
        m_axi_in_V_RUSER => m_axi_in_V_RUSER,
        m_axi_in_V_RRESP => m_axi_in_V_RRESP,
        m_axi_in_V_BVALID => ap_const_logic_0,
        m_axi_in_V_BREADY => grp_Mem2Stream_fu_58_m_axi_in_V_BREADY,
        m_axi_in_V_BRESP => ap_const_lv2_0,
        m_axi_in_V_BID => ap_const_lv1_0,
        m_axi_in_V_BUSER => ap_const_lv1_0,
        in_V_offset => in_V_offset,
        out_V_V_din => grp_Mem2Stream_fu_58_out_V_V_din,
        out_V_V_full_n => inter0_V_V_full_n,
        out_V_V_write => grp_Mem2Stream_fu_58_out_V_V_write);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((grp_Mem2Stream_fu_58_ap_done = ap_const_logic_0) or (out_V_offset_out_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_Mem2Stream_fu_58_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_Mem2Stream_fu_58_ap_start_reg <= ap_const_logic_0;
            else
                if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_Mem2Stream_fu_58_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_Mem2Stream_fu_58_ap_ready = ap_const_logic_1)) then 
                    grp_Mem2Stream_fu_58_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, out_V_offset_out_full_n, ap_CS_fsm_state2, grp_Mem2Stream_fu_58_ap_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if ((not(((grp_Mem2Stream_fu_58_ap_done = ap_const_logic_0) or (out_V_offset_out_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state1_ignore_call12_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1_ignore_call12 <= ((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, out_V_offset_out_full_n, ap_CS_fsm_state2, grp_Mem2Stream_fu_58_ap_done)
    begin
        if ((not(((grp_Mem2Stream_fu_58_ap_done = ap_const_logic_0) or (out_V_offset_out_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    grp_Mem2Stream_fu_58_ap_start <= grp_Mem2Stream_fu_58_ap_start_reg;
    inter0_V_V_din <= grp_Mem2Stream_fu_58_out_V_V_din;

    inter0_V_V_write_assign_proc : process(ap_CS_fsm_state2, grp_Mem2Stream_fu_58_out_V_V_write)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            inter0_V_V_write <= grp_Mem2Stream_fu_58_out_V_V_write;
        else 
            inter0_V_V_write <= ap_const_logic_0;
        end if; 
    end process;


    internal_ap_ready_assign_proc : process(out_V_offset_out_full_n, ap_CS_fsm_state2, grp_Mem2Stream_fu_58_ap_done)
    begin
        if ((not(((grp_Mem2Stream_fu_58_ap_done = ap_const_logic_0) or (out_V_offset_out_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_in_V_ARADDR <= grp_Mem2Stream_fu_58_m_axi_in_V_ARADDR;
    m_axi_in_V_ARBURST <= grp_Mem2Stream_fu_58_m_axi_in_V_ARBURST;
    m_axi_in_V_ARCACHE <= grp_Mem2Stream_fu_58_m_axi_in_V_ARCACHE;
    m_axi_in_V_ARID <= grp_Mem2Stream_fu_58_m_axi_in_V_ARID;
    m_axi_in_V_ARLEN <= grp_Mem2Stream_fu_58_m_axi_in_V_ARLEN;
    m_axi_in_V_ARLOCK <= grp_Mem2Stream_fu_58_m_axi_in_V_ARLOCK;
    m_axi_in_V_ARPROT <= grp_Mem2Stream_fu_58_m_axi_in_V_ARPROT;
    m_axi_in_V_ARQOS <= grp_Mem2Stream_fu_58_m_axi_in_V_ARQOS;
    m_axi_in_V_ARREGION <= grp_Mem2Stream_fu_58_m_axi_in_V_ARREGION;
    m_axi_in_V_ARSIZE <= grp_Mem2Stream_fu_58_m_axi_in_V_ARSIZE;
    m_axi_in_V_ARUSER <= grp_Mem2Stream_fu_58_m_axi_in_V_ARUSER;

    m_axi_in_V_ARVALID_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, grp_Mem2Stream_fu_58_m_axi_in_V_ARVALID)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            m_axi_in_V_ARVALID <= grp_Mem2Stream_fu_58_m_axi_in_V_ARVALID;
        else 
            m_axi_in_V_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_in_V_AWADDR <= ap_const_lv64_0;
    m_axi_in_V_AWBURST <= ap_const_lv2_0;
    m_axi_in_V_AWCACHE <= ap_const_lv4_0;
    m_axi_in_V_AWID <= ap_const_lv1_0;
    m_axi_in_V_AWLEN <= ap_const_lv32_0;
    m_axi_in_V_AWLOCK <= ap_const_lv2_0;
    m_axi_in_V_AWPROT <= ap_const_lv3_0;
    m_axi_in_V_AWQOS <= ap_const_lv4_0;
    m_axi_in_V_AWREGION <= ap_const_lv4_0;
    m_axi_in_V_AWSIZE <= ap_const_lv3_0;
    m_axi_in_V_AWUSER <= ap_const_lv1_0;
    m_axi_in_V_AWVALID <= ap_const_logic_0;
    m_axi_in_V_BREADY <= ap_const_logic_0;

    m_axi_in_V_RREADY_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, grp_Mem2Stream_fu_58_m_axi_in_V_RREADY)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            m_axi_in_V_RREADY <= grp_Mem2Stream_fu_58_m_axi_in_V_RREADY;
        else 
            m_axi_in_V_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_in_V_WDATA <= ap_const_lv64_0;
    m_axi_in_V_WID <= ap_const_lv1_0;
    m_axi_in_V_WLAST <= ap_const_logic_0;
    m_axi_in_V_WSTRB <= ap_const_lv8_0;
    m_axi_in_V_WUSER <= ap_const_lv1_0;
    m_axi_in_V_WVALID <= ap_const_logic_0;

    out_V_offset_out_blk_n_assign_proc : process(out_V_offset_out_full_n, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            out_V_offset_out_blk_n <= out_V_offset_out_full_n;
        else 
            out_V_offset_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_V_offset_out_din <= out_V_offset;

    out_V_offset_out_write_assign_proc : process(out_V_offset_out_full_n, ap_CS_fsm_state2, grp_Mem2Stream_fu_58_ap_done)
    begin
        if ((not(((grp_Mem2Stream_fu_58_ap_done = ap_const_logic_0) or (out_V_offset_out_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            out_V_offset_out_write <= ap_const_logic_1;
        else 
            out_V_offset_out_write <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_full_n = ap_const_logic_0) and (start_once_reg = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
