// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _StreamingMaxPool_Bat_1_HH_
#define _StreamingMaxPool_Bat_1_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "StreamingMaxPool_1.h"

namespace ap_rtl {

struct StreamingMaxPool_Bat_1 : public sc_module {
    // Port declarations 16
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_in< sc_logic > start_full_n;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_logic > start_out;
    sc_out< sc_logic > start_write;
    sc_in< sc_lv<128> > in_V_V_dout;
    sc_in< sc_logic > in_V_V_empty_n;
    sc_out< sc_logic > in_V_V_read;
    sc_out< sc_lv<128> > out_V_V_din;
    sc_in< sc_logic > out_V_V_full_n;
    sc_out< sc_logic > out_V_V_write;


    // Module declarations
    StreamingMaxPool_Bat_1(sc_module_name name);
    SC_HAS_PROCESS(StreamingMaxPool_Bat_1);

    ~StreamingMaxPool_Bat_1();

    sc_trace_file* mVcdFile;

    StreamingMaxPool_1* grp_StreamingMaxPool_1_fu_18;
    sc_signal< sc_logic > real_start;
    sc_signal< sc_logic > start_once_reg;
    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > internal_ap_ready;
    sc_signal< sc_logic > grp_StreamingMaxPool_1_fu_18_ap_start;
    sc_signal< sc_logic > grp_StreamingMaxPool_1_fu_18_ap_done;
    sc_signal< sc_logic > grp_StreamingMaxPool_1_fu_18_ap_idle;
    sc_signal< sc_logic > grp_StreamingMaxPool_1_fu_18_ap_ready;
    sc_signal< sc_logic > grp_StreamingMaxPool_1_fu_18_in_V_V_read;
    sc_signal< sc_lv<128> > grp_StreamingMaxPool_1_fu_18_out_V_V_din;
    sc_signal< sc_logic > grp_StreamingMaxPool_1_fu_18_out_V_V_write;
    sc_signal< sc_logic > grp_StreamingMaxPool_1_fu_18_ap_start_reg;
    sc_signal< bool > ap_block_state1_ignore_call2;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<2> > ap_NS_fsm;
    sc_signal< bool > ap_block_state1;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<2> ap_ST_fsm_state1;
    static const sc_lv<2> ap_ST_fsm_state2;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_block_state1();
    void thread_ap_block_state1_ignore_call2();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_grp_StreamingMaxPool_1_fu_18_ap_start();
    void thread_in_V_V_read();
    void thread_internal_ap_ready();
    void thread_out_V_V_din();
    void thread_out_V_V_write();
    void thread_real_start();
    void thread_start_out();
    void thread_start_write();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
