// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module NaivePopCount (
        ap_clk,
        ap_rst,
        in_V_read,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [31:0] in_V_read;
output  [6:0] ap_return;
input   ap_ce;

reg[6:0] ap_return;

reg   [0:0] tmp_1404_reg_719;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_pp0_stage0_11001;
wire   [1:0] tmp_211_fu_126_p2;
reg   [1:0] tmp_211_reg_724;
reg   [0:0] tmp_1408_reg_729;
wire   [1:0] tmp2_fu_182_p2;
reg   [1:0] tmp2_reg_734;
reg   [0:0] tmp_1409_reg_739;
reg   [0:0] tmp_1410_reg_744;
reg   [0:0] tmp_1416_reg_749;
reg   [0:0] tmp_1416_reg_749_pp0_iter1_reg;
reg   [0:0] tmp_1416_reg_749_pp0_iter2_reg;
wire   [2:0] tmp7_fu_298_p2;
reg   [2:0] tmp7_reg_754;
reg   [2:0] tmp7_reg_754_pp0_iter1_reg;
reg   [0:0] tmp_1417_reg_759;
reg   [0:0] tmp_1417_reg_759_pp0_iter1_reg;
reg   [0:0] tmp_1418_reg_764;
reg   [0:0] tmp_1418_reg_764_pp0_iter1_reg;
reg   [0:0] tmp_1432_reg_769;
reg   [0:0] tmp_1432_reg_769_pp0_iter1_reg;
reg   [0:0] tmp_1432_reg_769_pp0_iter2_reg;
reg   [0:0] tmp_1432_reg_769_pp0_iter3_reg;
reg   [0:0] tmp_1432_reg_769_pp0_iter4_reg;
wire   [2:0] tmp15_fu_504_p2;
reg   [2:0] tmp15_reg_774;
reg   [2:0] tmp15_reg_774_pp0_iter1_reg;
reg   [2:0] tmp15_reg_774_pp0_iter2_reg;
reg   [2:0] tmp15_reg_774_pp0_iter3_reg;
wire   [2:0] tmp19_fu_530_p2;
reg   [2:0] tmp19_reg_779;
wire   [2:0] tmp22_fu_562_p2;
reg   [2:0] tmp22_reg_784;
wire   [3:0] tmp5_fu_602_p2;
reg   [3:0] tmp5_reg_789;
wire   [1:0] tmp6_fu_608_p2;
reg   [1:0] tmp6_reg_794;
wire   [3:0] tmp18_fu_620_p2;
reg   [3:0] tmp18_reg_799;
reg   [3:0] tmp18_reg_799_pp0_iter2_reg;
reg   [3:0] tmp18_reg_799_pp0_iter3_reg;
wire   [3:0] tmp_213_fu_637_p2;
reg   [3:0] tmp_213_reg_804;
wire   [1:0] tmp14_fu_649_p2;
reg   [1:0] tmp14_reg_809;
wire   [4:0] tmp12_fu_670_p2;
reg   [4:0] tmp12_reg_814;
wire   [4:0] tmp_214_fu_687_p2;
reg   [4:0] tmp_214_reg_819;
wire    ap_block_pp0_stage0;
wire   [0:0] tmp_1401_fu_80_p1;
wire   [0:0] tmp_1402_fu_84_p3;
wire   [0:0] tmp_1403_fu_100_p3;
wire   [1:0] tmp_cast_fu_92_p1;
wire   [1:0] tmp_371_cast_fu_108_p1;
wire   [1:0] tmp_fu_120_p2;
wire   [1:0] tmp_370_cast_fu_96_p1;
wire   [0:0] tmp_1405_fu_132_p3;
wire   [0:0] tmp_1406_fu_144_p3;
wire   [0:0] tmp_1407_fu_156_p3;
wire   [1:0] tmp_378_cast_cast_fu_152_p1;
wire   [1:0] tmp_379_cast_cast_fu_164_p1;
wire   [1:0] tmp3_fu_176_p2;
wire   [1:0] tmp_375_cast_cast_fu_140_p1;
wire   [0:0] tmp_1411_fu_204_p3;
wire   [0:0] tmp_1412_fu_216_p3;
wire   [0:0] tmp_1413_fu_228_p3;
wire   [0:0] tmp_1414_fu_240_p3;
wire   [0:0] tmp_1415_fu_252_p3;
wire   [1:0] tmp_387_cast_cast_fu_212_p1;
wire   [1:0] tmp_390_cast_cast_fu_224_p1;
wire   [1:0] tmp8_fu_272_p2;
wire   [1:0] tmp_394_cast_cast_fu_248_p1;
wire   [1:0] tmp_395_cast_cast_fu_260_p1;
wire   [1:0] tmp10_fu_282_p2;
wire   [1:0] tmp_391_cast_cast_fu_236_p1;
wire   [1:0] tmp9_fu_288_p2;
wire   [2:0] tmp9_cast_fu_294_p1;
wire   [2:0] tmp8_cast_fu_278_p1;
wire   [0:0] tmp_1419_fu_320_p3;
wire   [0:0] tmp_1420_fu_332_p3;
wire   [0:0] tmp_1421_fu_344_p3;
wire   [0:0] tmp_1422_fu_356_p3;
wire   [0:0] tmp_1423_fu_368_p3;
wire   [0:0] tmp_1424_fu_380_p3;
wire   [0:0] tmp_1425_fu_392_p3;
wire   [0:0] tmp_1426_fu_404_p3;
wire   [0:0] tmp_1427_fu_416_p3;
wire   [0:0] tmp_1428_fu_428_p3;
wire   [0:0] tmp_1429_fu_440_p3;
wire   [0:0] tmp_1430_fu_452_p3;
wire   [0:0] tmp_1431_fu_464_p3;
wire   [1:0] tmp_403_cast_cast_fu_328_p1;
wire   [1:0] tmp_406_cast_cast_fu_340_p1;
wire   [1:0] tmp16_fu_484_p2;
wire   [1:0] tmp_407_cast_cast_fu_352_p1;
wire   [1:0] tmp_410_cast_cast_fu_364_p1;
wire   [1:0] tmp17_fu_494_p2;
wire   [2:0] tmp17_cast_fu_500_p1;
wire   [2:0] tmp16_cast_fu_490_p1;
wire   [1:0] tmp_411_cast_cast_fu_376_p1;
wire   [1:0] tmp_414_cast_cast_fu_388_p1;
wire   [1:0] tmp20_fu_510_p2;
wire   [1:0] tmp_415_cast_cast_fu_400_p1;
wire   [1:0] tmp_418_cast_cast_fu_412_p1;
wire   [1:0] tmp21_fu_520_p2;
wire   [2:0] tmp21_cast_fu_526_p1;
wire   [2:0] tmp20_cast_fu_516_p1;
wire   [1:0] tmp_419_cast_cast_fu_424_p1;
wire   [1:0] tmp_422_cast_cast_fu_436_p1;
wire   [1:0] tmp23_fu_536_p2;
wire   [1:0] tmp_426_cast_cast_fu_460_p1;
wire   [1:0] tmp_427_cast_cast_fu_472_p1;
wire   [1:0] tmp25_fu_546_p2;
wire   [1:0] tmp_423_cast_cast_fu_448_p1;
wire   [1:0] tmp24_fu_552_p2;
wire   [2:0] tmp24_cast_fu_558_p1;
wire   [2:0] tmp23_cast_fu_542_p1;
wire   [2:0] tmp_373_cast_fu_568_p1;
wire   [2:0] tmp_374_cast_fu_571_p1;
wire   [2:0] tmp2_cast_fu_580_p1;
wire   [2:0] tmp1_fu_574_p2;
wire   [2:0] tmp_212_fu_583_p2;
wire   [3:0] tmp_381_cast_fu_589_p1;
wire   [3:0] tmp_382_cast_fu_593_p1;
wire   [1:0] tmp_383_cast_cast_fu_596_p1;
wire   [1:0] tmp_386_cast_cast_fu_599_p1;
wire   [3:0] tmp22_cast_fu_617_p1;
wire   [3:0] tmp19_cast_fu_614_p1;
wire   [3:0] tmp6_cast_fu_626_p1;
wire   [3:0] tmp7_cast_fu_634_p1;
wire   [3:0] tmp4_fu_629_p2;
wire   [1:0] tmp_399_cast_cast_fu_643_p1;
wire   [1:0] tmp_402_cast_cast_fu_646_p1;
wire   [4:0] tmp_397_cast_fu_655_p1;
wire   [4:0] tmp_398_cast_fu_658_p1;
wire   [4:0] tmp14_cast_fu_667_p1;
wire   [4:0] tmp13_fu_661_p2;
wire   [4:0] tmp15_cast_fu_676_p1;
wire   [4:0] tmp18_cast_fu_684_p1;
wire   [4:0] tmp11_fu_679_p2;
wire   [5:0] tmp_429_cast_fu_693_p1;
wire   [5:0] tmp_430_cast_fu_696_p1;
wire   [5:0] pct_V_s_fu_699_p2;
wire   [6:0] tmp_s_fu_705_p3;
wire   [6:0] agg_result_V_fu_713_p2;
reg    ap_ce_reg;
reg   [31:0] in_V_read_int_reg;
reg   [6:0] ap_return_int_reg;

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_int_reg[6 : 1] <= agg_result_V_fu_713_p2[6 : 1];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        in_V_read_int_reg <= in_V_read;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp12_reg_814 <= tmp12_fu_670_p2;
        tmp14_reg_809 <= tmp14_fu_649_p2;
        tmp15_reg_774 <= tmp15_fu_504_p2;
        tmp15_reg_774_pp0_iter1_reg <= tmp15_reg_774;
        tmp15_reg_774_pp0_iter2_reg <= tmp15_reg_774_pp0_iter1_reg;
        tmp15_reg_774_pp0_iter3_reg <= tmp15_reg_774_pp0_iter2_reg;
        tmp18_reg_799 <= tmp18_fu_620_p2;
        tmp18_reg_799_pp0_iter2_reg <= tmp18_reg_799;
        tmp18_reg_799_pp0_iter3_reg <= tmp18_reg_799_pp0_iter2_reg;
        tmp19_reg_779 <= tmp19_fu_530_p2;
        tmp22_reg_784 <= tmp22_fu_562_p2;
        tmp2_reg_734 <= tmp2_fu_182_p2;
        tmp5_reg_789 <= tmp5_fu_602_p2;
        tmp6_reg_794 <= tmp6_fu_608_p2;
        tmp7_reg_754 <= tmp7_fu_298_p2;
        tmp7_reg_754_pp0_iter1_reg <= tmp7_reg_754;
        tmp_1404_reg_719 <= in_V_read_int_reg[32'd3];
        tmp_1408_reg_729 <= in_V_read_int_reg[32'd7];
        tmp_1409_reg_739 <= in_V_read_int_reg[32'd8];
        tmp_1410_reg_744 <= in_V_read_int_reg[32'd9];
        tmp_1416_reg_749 <= in_V_read_int_reg[32'd15];
        tmp_1416_reg_749_pp0_iter1_reg <= tmp_1416_reg_749;
        tmp_1416_reg_749_pp0_iter2_reg <= tmp_1416_reg_749_pp0_iter1_reg;
        tmp_1417_reg_759 <= in_V_read_int_reg[32'd16];
        tmp_1417_reg_759_pp0_iter1_reg <= tmp_1417_reg_759;
        tmp_1418_reg_764 <= in_V_read_int_reg[32'd17];
        tmp_1418_reg_764_pp0_iter1_reg <= tmp_1418_reg_764;
        tmp_1432_reg_769 <= in_V_read_int_reg[32'd31];
        tmp_1432_reg_769_pp0_iter1_reg <= tmp_1432_reg_769;
        tmp_1432_reg_769_pp0_iter2_reg <= tmp_1432_reg_769_pp0_iter1_reg;
        tmp_1432_reg_769_pp0_iter3_reg <= tmp_1432_reg_769_pp0_iter2_reg;
        tmp_1432_reg_769_pp0_iter4_reg <= tmp_1432_reg_769_pp0_iter3_reg;
        tmp_211_reg_724 <= tmp_211_fu_126_p2;
        tmp_213_reg_804 <= tmp_213_fu_637_p2;
        tmp_214_reg_819 <= tmp_214_fu_687_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return = ap_return_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return = agg_result_V_fu_713_p2;
    end
end

assign agg_result_V_fu_713_p2 = ($signed(7'd96) + $signed(tmp_s_fu_705_p3));

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign pct_V_s_fu_699_p2 = (tmp_429_cast_fu_693_p1 + tmp_430_cast_fu_696_p1);

assign tmp10_fu_282_p2 = (tmp_394_cast_cast_fu_248_p1 + tmp_395_cast_cast_fu_260_p1);

assign tmp11_fu_679_p2 = (tmp15_cast_fu_676_p1 + tmp12_reg_814);

assign tmp12_fu_670_p2 = (tmp14_cast_fu_667_p1 + tmp13_fu_661_p2);

assign tmp13_fu_661_p2 = (tmp_397_cast_fu_655_p1 + tmp_398_cast_fu_658_p1);

assign tmp14_cast_fu_667_p1 = tmp14_reg_809;

assign tmp14_fu_649_p2 = (tmp_399_cast_cast_fu_643_p1 + tmp_402_cast_cast_fu_646_p1);

assign tmp15_cast_fu_676_p1 = tmp15_reg_774_pp0_iter3_reg;

assign tmp15_fu_504_p2 = (tmp17_cast_fu_500_p1 + tmp16_cast_fu_490_p1);

assign tmp16_cast_fu_490_p1 = tmp16_fu_484_p2;

assign tmp16_fu_484_p2 = (tmp_403_cast_cast_fu_328_p1 + tmp_406_cast_cast_fu_340_p1);

assign tmp17_cast_fu_500_p1 = tmp17_fu_494_p2;

assign tmp17_fu_494_p2 = (tmp_407_cast_cast_fu_352_p1 + tmp_410_cast_cast_fu_364_p1);

assign tmp18_cast_fu_684_p1 = tmp18_reg_799_pp0_iter3_reg;

assign tmp18_fu_620_p2 = (tmp22_cast_fu_617_p1 + tmp19_cast_fu_614_p1);

assign tmp19_cast_fu_614_p1 = tmp19_reg_779;

assign tmp19_fu_530_p2 = (tmp21_cast_fu_526_p1 + tmp20_cast_fu_516_p1);

assign tmp1_fu_574_p2 = (tmp_373_cast_fu_568_p1 + tmp_374_cast_fu_571_p1);

assign tmp20_cast_fu_516_p1 = tmp20_fu_510_p2;

assign tmp20_fu_510_p2 = (tmp_411_cast_cast_fu_376_p1 + tmp_414_cast_cast_fu_388_p1);

assign tmp21_cast_fu_526_p1 = tmp21_fu_520_p2;

assign tmp21_fu_520_p2 = (tmp_415_cast_cast_fu_400_p1 + tmp_418_cast_cast_fu_412_p1);

assign tmp22_cast_fu_617_p1 = tmp22_reg_784;

assign tmp22_fu_562_p2 = (tmp24_cast_fu_558_p1 + tmp23_cast_fu_542_p1);

assign tmp23_cast_fu_542_p1 = tmp23_fu_536_p2;

assign tmp23_fu_536_p2 = (tmp_419_cast_cast_fu_424_p1 + tmp_422_cast_cast_fu_436_p1);

assign tmp24_cast_fu_558_p1 = tmp24_fu_552_p2;

assign tmp24_fu_552_p2 = (tmp25_fu_546_p2 + tmp_423_cast_cast_fu_448_p1);

assign tmp25_fu_546_p2 = (tmp_426_cast_cast_fu_460_p1 + tmp_427_cast_cast_fu_472_p1);

assign tmp2_cast_fu_580_p1 = tmp2_reg_734;

assign tmp2_fu_182_p2 = (tmp3_fu_176_p2 + tmp_375_cast_cast_fu_140_p1);

assign tmp3_fu_176_p2 = (tmp_378_cast_cast_fu_152_p1 + tmp_379_cast_cast_fu_164_p1);

assign tmp4_fu_629_p2 = (tmp6_cast_fu_626_p1 + tmp5_reg_789);

assign tmp5_fu_602_p2 = (tmp_381_cast_fu_589_p1 + tmp_382_cast_fu_593_p1);

assign tmp6_cast_fu_626_p1 = tmp6_reg_794;

assign tmp6_fu_608_p2 = (tmp_383_cast_cast_fu_596_p1 + tmp_386_cast_cast_fu_599_p1);

assign tmp7_cast_fu_634_p1 = tmp7_reg_754_pp0_iter1_reg;

assign tmp7_fu_298_p2 = (tmp9_cast_fu_294_p1 + tmp8_cast_fu_278_p1);

assign tmp8_cast_fu_278_p1 = tmp8_fu_272_p2;

assign tmp8_fu_272_p2 = (tmp_387_cast_cast_fu_212_p1 + tmp_390_cast_cast_fu_224_p1);

assign tmp9_cast_fu_294_p1 = tmp9_fu_288_p2;

assign tmp9_fu_288_p2 = (tmp10_fu_282_p2 + tmp_391_cast_cast_fu_236_p1);

assign tmp_1401_fu_80_p1 = in_V_read_int_reg[0:0];

assign tmp_1402_fu_84_p3 = in_V_read_int_reg[32'd1];

assign tmp_1403_fu_100_p3 = in_V_read_int_reg[32'd2];

assign tmp_1405_fu_132_p3 = in_V_read_int_reg[32'd4];

assign tmp_1406_fu_144_p3 = in_V_read_int_reg[32'd5];

assign tmp_1407_fu_156_p3 = in_V_read_int_reg[32'd6];

assign tmp_1411_fu_204_p3 = in_V_read_int_reg[32'd10];

assign tmp_1412_fu_216_p3 = in_V_read_int_reg[32'd11];

assign tmp_1413_fu_228_p3 = in_V_read_int_reg[32'd12];

assign tmp_1414_fu_240_p3 = in_V_read_int_reg[32'd13];

assign tmp_1415_fu_252_p3 = in_V_read_int_reg[32'd14];

assign tmp_1419_fu_320_p3 = in_V_read_int_reg[32'd18];

assign tmp_1420_fu_332_p3 = in_V_read_int_reg[32'd19];

assign tmp_1421_fu_344_p3 = in_V_read_int_reg[32'd20];

assign tmp_1422_fu_356_p3 = in_V_read_int_reg[32'd21];

assign tmp_1423_fu_368_p3 = in_V_read_int_reg[32'd22];

assign tmp_1424_fu_380_p3 = in_V_read_int_reg[32'd23];

assign tmp_1425_fu_392_p3 = in_V_read_int_reg[32'd24];

assign tmp_1426_fu_404_p3 = in_V_read_int_reg[32'd25];

assign tmp_1427_fu_416_p3 = in_V_read_int_reg[32'd26];

assign tmp_1428_fu_428_p3 = in_V_read_int_reg[32'd27];

assign tmp_1429_fu_440_p3 = in_V_read_int_reg[32'd28];

assign tmp_1430_fu_452_p3 = in_V_read_int_reg[32'd29];

assign tmp_1431_fu_464_p3 = in_V_read_int_reg[32'd30];

assign tmp_211_fu_126_p2 = (tmp_fu_120_p2 + tmp_370_cast_fu_96_p1);

assign tmp_212_fu_583_p2 = (tmp2_cast_fu_580_p1 + tmp1_fu_574_p2);

assign tmp_213_fu_637_p2 = (tmp7_cast_fu_634_p1 + tmp4_fu_629_p2);

assign tmp_214_fu_687_p2 = (tmp18_cast_fu_684_p1 + tmp11_fu_679_p2);

assign tmp_370_cast_fu_96_p1 = tmp_1402_fu_84_p3;

assign tmp_371_cast_fu_108_p1 = tmp_1403_fu_100_p3;

assign tmp_373_cast_fu_568_p1 = tmp_211_reg_724;

assign tmp_374_cast_fu_571_p1 = tmp_1404_reg_719;

assign tmp_375_cast_cast_fu_140_p1 = tmp_1405_fu_132_p3;

assign tmp_378_cast_cast_fu_152_p1 = tmp_1406_fu_144_p3;

assign tmp_379_cast_cast_fu_164_p1 = tmp_1407_fu_156_p3;

assign tmp_381_cast_fu_589_p1 = tmp_212_fu_583_p2;

assign tmp_382_cast_fu_593_p1 = tmp_1408_reg_729;

assign tmp_383_cast_cast_fu_596_p1 = tmp_1409_reg_739;

assign tmp_386_cast_cast_fu_599_p1 = tmp_1410_reg_744;

assign tmp_387_cast_cast_fu_212_p1 = tmp_1411_fu_204_p3;

assign tmp_390_cast_cast_fu_224_p1 = tmp_1412_fu_216_p3;

assign tmp_391_cast_cast_fu_236_p1 = tmp_1413_fu_228_p3;

assign tmp_394_cast_cast_fu_248_p1 = tmp_1414_fu_240_p3;

assign tmp_395_cast_cast_fu_260_p1 = tmp_1415_fu_252_p3;

assign tmp_397_cast_fu_655_p1 = tmp_213_reg_804;

assign tmp_398_cast_fu_658_p1 = tmp_1416_reg_749_pp0_iter2_reg;

assign tmp_399_cast_cast_fu_643_p1 = tmp_1417_reg_759_pp0_iter1_reg;

assign tmp_402_cast_cast_fu_646_p1 = tmp_1418_reg_764_pp0_iter1_reg;

assign tmp_403_cast_cast_fu_328_p1 = tmp_1419_fu_320_p3;

assign tmp_406_cast_cast_fu_340_p1 = tmp_1420_fu_332_p3;

assign tmp_407_cast_cast_fu_352_p1 = tmp_1421_fu_344_p3;

assign tmp_410_cast_cast_fu_364_p1 = tmp_1422_fu_356_p3;

assign tmp_411_cast_cast_fu_376_p1 = tmp_1423_fu_368_p3;

assign tmp_414_cast_cast_fu_388_p1 = tmp_1424_fu_380_p3;

assign tmp_415_cast_cast_fu_400_p1 = tmp_1425_fu_392_p3;

assign tmp_418_cast_cast_fu_412_p1 = tmp_1426_fu_404_p3;

assign tmp_419_cast_cast_fu_424_p1 = tmp_1427_fu_416_p3;

assign tmp_422_cast_cast_fu_436_p1 = tmp_1428_fu_428_p3;

assign tmp_423_cast_cast_fu_448_p1 = tmp_1429_fu_440_p3;

assign tmp_426_cast_cast_fu_460_p1 = tmp_1430_fu_452_p3;

assign tmp_427_cast_cast_fu_472_p1 = tmp_1431_fu_464_p3;

assign tmp_429_cast_fu_693_p1 = tmp_214_reg_819;

assign tmp_430_cast_fu_696_p1 = tmp_1432_reg_769_pp0_iter4_reg;

assign tmp_cast_fu_92_p1 = tmp_1401_fu_80_p1;

assign tmp_fu_120_p2 = (tmp_cast_fu_92_p1 + tmp_371_cast_fu_108_p1);

assign tmp_s_fu_705_p3 = {{pct_V_s_fu_699_p2}, {1'd0}};

always @ (posedge ap_clk) begin
    ap_return_int_reg[0] <= 1'b0;
end

endmodule //NaivePopCount
