// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module StreamingConvolution (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        in_V_V_dout,
        in_V_V_empty_n,
        in_V_V_read,
        out_V_V_din,
        out_V_V_full_n,
        out_V_V_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_pp0_stage0 = 4'd2;
parameter    ap_ST_fsm_pp0_stage1 = 4'd4;
parameter    ap_ST_fsm_state7 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [63:0] in_V_V_dout;
input   in_V_V_empty_n;
output   in_V_V_read;
output  [63:0] out_V_V_din;
input   out_V_V_full_n;
output   out_V_V_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg in_V_V_read;
reg[63:0] out_V_V_din;
reg out_V_V_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    in_V_V_blk_n;
wire    ap_CS_fsm_pp0_stage1;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage1;
reg   [0:0] tmp_reg_875;
reg   [0:0] tmp_s_reg_884;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] or_cond_reg_925;
reg    out_V_V_blk_n;
reg   [0:0] tmp_s_reg_884_pp0_iter1_reg;
reg   [0:0] tmp_140_reg_888;
reg   [0:0] tmp_140_reg_888_pp0_iter1_reg;
reg    ap_enable_reg_pp0_iter2;
reg   [12:0] i_reg_389;
wire   [31:0] grp_fu_434_p2;
reg   [31:0] reg_460;
wire    ap_block_state2_pp0_stage0_iter0;
reg    ap_predicate_op168_read_state4;
reg    ap_block_state4_pp0_stage0_iter1;
reg    ap_predicate_op228_write_state6;
reg    ap_block_state6_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] tmp_fu_534_p2;
wire   [0:0] tmp_s_fu_546_p2;
wire   [0:0] or_cond_fu_664_p2;
reg   [31:0] reg_464;
reg    ap_predicate_op110_read_state3;
reg    ap_predicate_op128_read_state3;
reg    ap_block_state3_pp0_stage1_iter0;
reg    ap_predicate_op206_write_state5;
reg    ap_block_state5_pp0_stage1_iter1;
reg    ap_block_pp0_stage1_11001;
reg   [63:0] reg_468;
wire   [31:0] grp_fu_449_p2;
reg   [31:0] reg_480;
wire   [0:0] grp_fu_484_p2;
wire   [12:0] i_s_fu_540_p2;
reg   [12:0] i_s_reg_879;
wire   [0:0] tmp_140_fu_555_p2;
wire   [1:0] tmp_1382_fu_570_p1;
reg   [1:0] tmp_1382_reg_892;
wire   [31:0] current_line_in_bloc_fu_580_p2;
reg   [31:0] current_line_in_bloc_reg_897;
wire   [0:0] tmp_145_fu_592_p2;
reg   [0:0] tmp_145_reg_902;
wire   [0:0] tmp_147_fu_603_p2;
reg   [0:0] tmp_147_reg_906;
wire   [0:0] tmp_149_fu_623_p2;
reg   [0:0] tmp_149_reg_910;
wire   [31:0] ofm_y_2_fu_637_p2;
reg   [31:0] ofm_y_2_reg_914;
wire   [0:0] tmp_150_fu_643_p2;
reg   [0:0] tmp_150_reg_919;
reg   [0:0] or_cond_reg_925_pp0_iter1_reg;
wire   [31:0] counter_internal_blo_19_fu_673_p2;
reg   [31:0] counter_internal_blo_19_reg_929;
wire   [63:0] tmp_144_fu_679_p1;
reg   [63:0] tmp_144_reg_935;
reg   [0:0] tmp_156_reg_963;
reg   [0:0] tmp_146_reg_967;
wire   [1:0] tmp_143_fu_747_p2;
reg   [1:0] tmp_143_reg_971;
wire   [63:0] inputBuf_0_0_V_q0;
reg   [63:0] inputBuf_0_0_V_loa_reg_977;
wire   [63:0] inputBuf_1_0_V_q0;
reg   [63:0] inputBuf_1_0_V_loa_reg_982;
wire   [63:0] inputBuf_2_0_V_q0;
reg   [63:0] inputBuf_2_0_V_loa_reg_987;
wire   [63:0] inputBuf_3_0_V_q0;
reg   [63:0] inputBuf_3_0_V_loa_reg_992;
wire   [1:0] tmp_1384_fu_767_p1;
reg   [1:0] tmp_1384_reg_1017;
reg   [4:0] inputBuf_0_1_V_add_12_reg_1021;
reg   [4:0] inputBuf_1_1_V_add_12_reg_1026;
reg   [4:0] inputBuf_2_1_V_add_12_reg_1031;
reg   [4:0] inputBuf_3_1_V_add_12_reg_1036;
wire   [1:0] tmp_1381_fu_783_p1;
reg   [1:0] tmp_1381_reg_1041;
reg   [4:0] inputBuf_0_1_V_add_reg_1045;
reg   [4:0] inputBuf_1_1_V_add_reg_1050;
reg   [4:0] inputBuf_2_1_V_add_reg_1055;
reg   [4:0] inputBuf_3_1_V_add_reg_1060;
wire   [63:0] inputBuf_0_1_V_q0;
reg   [63:0] inputBuf_0_1_V_loa_reg_1065;
wire   [63:0] inputBuf_1_1_V_q0;
reg   [63:0] inputBuf_1_1_V_loa_reg_1070;
wire   [63:0] inputBuf_2_1_V_q0;
reg   [63:0] inputBuf_2_1_V_loa_reg_1075;
wire   [63:0] inputBuf_3_1_V_q0;
reg   [63:0] inputBuf_3_1_V_loa_reg_1080;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_block_pp0_stage1_subdone;
wire   [4:0] inputBuf_0_0_V_address0;
reg    inputBuf_0_0_V_ce0;
reg   [4:0] inputBuf_0_0_V_address1;
reg    inputBuf_0_0_V_ce1;
reg    inputBuf_0_0_V_we1;
wire   [4:0] inputBuf_0_1_V_address0;
reg    inputBuf_0_1_V_ce0;
reg   [4:0] inputBuf_0_1_V_address1;
reg    inputBuf_0_1_V_ce1;
reg    inputBuf_0_1_V_we1;
wire   [4:0] inputBuf_1_0_V_address0;
reg    inputBuf_1_0_V_ce0;
reg   [4:0] inputBuf_1_0_V_address1;
reg    inputBuf_1_0_V_ce1;
reg    inputBuf_1_0_V_we1;
wire   [4:0] inputBuf_1_1_V_address0;
reg    inputBuf_1_1_V_ce0;
reg   [4:0] inputBuf_1_1_V_address1;
reg    inputBuf_1_1_V_ce1;
reg    inputBuf_1_1_V_we1;
wire   [4:0] inputBuf_2_0_V_address0;
reg    inputBuf_2_0_V_ce0;
reg   [4:0] inputBuf_2_0_V_address1;
reg    inputBuf_2_0_V_ce1;
reg    inputBuf_2_0_V_we1;
wire   [4:0] inputBuf_2_1_V_address0;
reg    inputBuf_2_1_V_ce0;
reg   [4:0] inputBuf_2_1_V_address1;
reg    inputBuf_2_1_V_ce1;
reg    inputBuf_2_1_V_we1;
wire   [4:0] inputBuf_3_0_V_address0;
reg    inputBuf_3_0_V_ce0;
reg   [4:0] inputBuf_3_0_V_address1;
reg    inputBuf_3_0_V_ce1;
reg    inputBuf_3_0_V_we1;
wire   [4:0] inputBuf_3_1_V_address0;
reg    inputBuf_3_1_V_ce0;
reg   [4:0] inputBuf_3_1_V_address1;
reg    inputBuf_3_1_V_ce1;
reg    inputBuf_3_1_V_we1;
reg   [12:0] ap_phi_mux_i_phi_fu_393_p4;
wire   [63:0] tmp_153_fu_755_p1;
wire   [63:0] tmp_139_fu_771_p1;
wire   [63:0] tmp_V_50_fu_787_p6;
reg    ap_block_pp0_stage1_01001;
wire   [63:0] tmp_V_51_fu_797_p6;
reg    ap_block_pp0_stage0_01001;
reg   [31:0] ofm_y_1_fu_76;
wire   [31:0] p_ofm_y_2_fu_693_p3;
reg   [31:0] ofm_x_1_fu_80;
wire   [31:0] ofm_x_2_fu_617_p2;
reg   [31:0] k_y_1_fu_84;
wire   [31:0] k_y_2_fu_574_p2;
reg   [31:0] inp_s_fu_88;
wire   [31:0] p_inp_s_fu_686_p3;
wire   [31:0] inp_1_fu_726_p2;
reg   [31:0] k_x_1_fu_92;
wire   [31:0] k_x_2_fu_586_p2;
reg   [31:0] read_block_1_fu_96;
wire   [31:0] grp_fu_443_p2;
reg   [31:0] current_block_write_s_fu_100;
wire   [31:0] grp_fu_501_p3;
reg   [31:0] current_line_1_fu_104;
reg   [31:0] counter_internal_blo_fu_108;
wire   [31:0] p_s_fu_714_p3;
wire   [0:0] grp_fu_495_p2;
wire   [0:0] tmp_151_fu_652_p2;
wire   [0:0] tmp_152_fu_658_p2;
wire   [0:0] tmp_159_fu_709_p2;
wire   [1:0] tmp_1383_fu_737_p1;
wire   [1:0] tmp1_fu_741_p2;
wire    ap_CS_fsm_state7;
reg   [3:0] ap_NS_fsm;
reg    ap_block_pp0;
reg    ap_predicate_op96_load_state3;
reg    ap_enable_operation_96;
reg    ap_enable_state3_pp0_iter0_stage1;
reg    ap_predicate_op147_load_state4;
reg    ap_enable_operation_147;
reg    ap_enable_state4_pp0_iter1_stage0;
reg    ap_predicate_op176_store_state4;
reg    ap_enable_operation_176;
reg    ap_predicate_op199_store_state4;
reg    ap_enable_operation_199;
reg    ap_predicate_op98_load_state3;
reg    ap_enable_operation_98;
reg    ap_predicate_op148_load_state4;
reg    ap_enable_operation_148;
reg    ap_predicate_op175_store_state4;
reg    ap_enable_operation_175;
reg    ap_predicate_op198_store_state4;
reg    ap_enable_operation_198;
reg    ap_predicate_op100_load_state3;
reg    ap_enable_operation_100;
reg    ap_predicate_op149_load_state4;
reg    ap_enable_operation_149;
reg    ap_predicate_op174_store_state4;
reg    ap_enable_operation_174;
reg    ap_predicate_op197_store_state4;
reg    ap_enable_operation_197;
reg    ap_predicate_op102_load_state3;
reg    ap_enable_operation_102;
reg    ap_predicate_op150_load_state4;
reg    ap_enable_operation_150;
reg    ap_predicate_op177_store_state4;
reg    ap_enable_operation_177;
reg    ap_predicate_op200_store_state4;
reg    ap_enable_operation_200;
reg    ap_predicate_op152_load_state4;
reg    ap_enable_operation_152;
reg    ap_predicate_op207_load_state5;
reg    ap_enable_operation_207;
reg    ap_enable_state5_pp0_iter1_stage1;
reg    ap_predicate_op215_store_state5;
reg    ap_enable_operation_215;
reg    ap_predicate_op223_store_state5;
reg    ap_enable_operation_223;
reg    ap_predicate_op154_load_state4;
reg    ap_enable_operation_154;
reg    ap_predicate_op208_load_state5;
reg    ap_enable_operation_208;
reg    ap_predicate_op213_store_state5;
reg    ap_enable_operation_213;
reg    ap_predicate_op221_store_state5;
reg    ap_enable_operation_221;
reg    ap_predicate_op156_load_state4;
reg    ap_enable_operation_156;
reg    ap_predicate_op209_load_state5;
reg    ap_enable_operation_209;
reg    ap_predicate_op211_store_state5;
reg    ap_enable_operation_211;
reg    ap_predicate_op219_store_state5;
reg    ap_enable_operation_219;
reg    ap_predicate_op158_load_state4;
reg    ap_enable_operation_158;
reg    ap_predicate_op210_load_state5;
reg    ap_enable_operation_210;
reg    ap_predicate_op217_store_state5;
reg    ap_enable_operation_217;
reg    ap_predicate_op225_store_state5;
reg    ap_enable_operation_225;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_550;
reg    ap_condition_81;
reg    ap_condition_595;
reg    ap_condition_96;
reg    ap_condition_561;
reg    ap_condition_606;
reg    ap_condition_572;
reg    ap_condition_616;
reg    ap_condition_583;
reg    ap_condition_626;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
end

StreamingConvolution_inputBuf_0_0_V #(
    .DataWidth( 64 ),
    .AddressRange( 30 ),
    .AddressWidth( 5 ))
inputBuf_0_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_0_0_V_address0),
    .ce0(inputBuf_0_0_V_ce0),
    .q0(inputBuf_0_0_V_q0),
    .address1(inputBuf_0_0_V_address1),
    .ce1(inputBuf_0_0_V_ce1),
    .we1(inputBuf_0_0_V_we1),
    .d1(reg_468)
);

StreamingConvolution_inputBuf_0_0_V #(
    .DataWidth( 64 ),
    .AddressRange( 30 ),
    .AddressWidth( 5 ))
inputBuf_0_1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_0_1_V_address0),
    .ce0(inputBuf_0_1_V_ce0),
    .q0(inputBuf_0_1_V_q0),
    .address1(inputBuf_0_1_V_address1),
    .ce1(inputBuf_0_1_V_ce1),
    .we1(inputBuf_0_1_V_we1),
    .d1(reg_468)
);

StreamingConvolution_inputBuf_0_0_V #(
    .DataWidth( 64 ),
    .AddressRange( 30 ),
    .AddressWidth( 5 ))
inputBuf_1_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_1_0_V_address0),
    .ce0(inputBuf_1_0_V_ce0),
    .q0(inputBuf_1_0_V_q0),
    .address1(inputBuf_1_0_V_address1),
    .ce1(inputBuf_1_0_V_ce1),
    .we1(inputBuf_1_0_V_we1),
    .d1(reg_468)
);

StreamingConvolution_inputBuf_0_0_V #(
    .DataWidth( 64 ),
    .AddressRange( 30 ),
    .AddressWidth( 5 ))
inputBuf_1_1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_1_1_V_address0),
    .ce0(inputBuf_1_1_V_ce0),
    .q0(inputBuf_1_1_V_q0),
    .address1(inputBuf_1_1_V_address1),
    .ce1(inputBuf_1_1_V_ce1),
    .we1(inputBuf_1_1_V_we1),
    .d1(reg_468)
);

StreamingConvolution_inputBuf_0_0_V #(
    .DataWidth( 64 ),
    .AddressRange( 30 ),
    .AddressWidth( 5 ))
inputBuf_2_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_2_0_V_address0),
    .ce0(inputBuf_2_0_V_ce0),
    .q0(inputBuf_2_0_V_q0),
    .address1(inputBuf_2_0_V_address1),
    .ce1(inputBuf_2_0_V_ce1),
    .we1(inputBuf_2_0_V_we1),
    .d1(reg_468)
);

StreamingConvolution_inputBuf_0_0_V #(
    .DataWidth( 64 ),
    .AddressRange( 30 ),
    .AddressWidth( 5 ))
inputBuf_2_1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_2_1_V_address0),
    .ce0(inputBuf_2_1_V_ce0),
    .q0(inputBuf_2_1_V_q0),
    .address1(inputBuf_2_1_V_address1),
    .ce1(inputBuf_2_1_V_ce1),
    .we1(inputBuf_2_1_V_we1),
    .d1(reg_468)
);

StreamingConvolution_inputBuf_0_0_V #(
    .DataWidth( 64 ),
    .AddressRange( 30 ),
    .AddressWidth( 5 ))
inputBuf_3_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_3_0_V_address0),
    .ce0(inputBuf_3_0_V_ce0),
    .q0(inputBuf_3_0_V_q0),
    .address1(inputBuf_3_0_V_address1),
    .ce1(inputBuf_3_0_V_ce1),
    .we1(inputBuf_3_0_V_we1),
    .d1(reg_468)
);

StreamingConvolution_inputBuf_0_0_V #(
    .DataWidth( 64 ),
    .AddressRange( 30 ),
    .AddressWidth( 5 ))
inputBuf_3_1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_3_1_V_address0),
    .ce0(inputBuf_3_1_V_ce0),
    .q0(inputBuf_3_1_V_q0),
    .address1(inputBuf_3_1_V_address1),
    .ce1(inputBuf_3_1_V_ce1),
    .we1(inputBuf_3_1_V_we1),
    .d1(reg_468)
);

BlackBoxJam_mux_42_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .din2_WIDTH( 64 ),
    .din3_WIDTH( 64 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 64 ))
BlackBoxJam_mux_42_64_1_1_U89(
    .din0(inputBuf_0_0_V_loa_reg_977),
    .din1(inputBuf_1_0_V_loa_reg_982),
    .din2(inputBuf_2_0_V_loa_reg_987),
    .din3(inputBuf_3_0_V_loa_reg_992),
    .din4(tmp_143_reg_971),
    .dout(tmp_V_50_fu_787_p6)
);

BlackBoxJam_mux_42_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .din2_WIDTH( 64 ),
    .din3_WIDTH( 64 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 64 ))
BlackBoxJam_mux_42_64_1_1_U90(
    .din0(inputBuf_0_1_V_loa_reg_1065),
    .din1(inputBuf_1_1_V_loa_reg_1070),
    .din2(inputBuf_2_1_V_loa_reg_1075),
    .din3(inputBuf_3_1_V_loa_reg_1080),
    .din4(tmp_143_reg_971),
    .dout(tmp_V_51_fu_797_p6)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_reg_884 == 1'd0) & (tmp_reg_875 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        counter_internal_blo_fu_108 <= p_s_fu_714_p3;
    end else if ((((grp_fu_484_p2 == 1'd1) & (tmp_s_reg_884 == 1'd1) & (tmp_reg_875 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | (~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        counter_internal_blo_fu_108 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((((or_cond_reg_925 == 1'd1) & (tmp_156_reg_963 == 1'd1) & (tmp_s_reg_884 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_146_reg_967 == 1'd1) & (tmp_s_reg_884 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        current_block_write_s_fu_100 <= grp_fu_501_p3;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        current_block_write_s_fu_100 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((((or_cond_reg_925 == 1'd1) & (tmp_s_reg_884 == 1'd0) & (grp_fu_484_p2 == 1'd0) & (tmp_reg_875 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((tmp_s_reg_884 == 1'd1) & (grp_fu_484_p2 == 1'd0) & (tmp_reg_875 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        current_line_1_fu_104 <= reg_460;
    end else if ((((or_cond_reg_925 == 1'd1) & (grp_fu_484_p2 == 1'd1) & (tmp_s_reg_884 == 1'd0) & (tmp_reg_875 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((grp_fu_484_p2 == 1'd1) & (tmp_s_reg_884 == 1'd1) & (tmp_reg_875 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | (~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        current_line_1_fu_104 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_reg_389 <= 13'd0;
    end else if (((tmp_reg_875 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        i_reg_389 <= i_s_reg_879;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_reg_884 == 1'd1) & (tmp_reg_875 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        inp_s_fu_88 <= inp_1_fu_726_p2;
    end else if (((tmp_140_reg_888 == 1'd1) & (tmp_149_reg_910 == 1'd1) & (tmp_147_reg_906 == 1'd1) & (tmp_145_reg_902 == 1'd1) & (tmp_s_reg_884 == 1'd0) & (tmp_reg_875 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        inp_s_fu_88 <= p_inp_s_fu_686_p3;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        inp_s_fu_88 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_140_fu_555_p2 == 1'd1) & (tmp_145_fu_592_p2 == 1'd0) & (tmp_s_fu_546_p2 == 1'd0) & (tmp_fu_534_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_x_1_fu_92 <= k_x_2_fu_586_p2;
    end else if ((((tmp_145_fu_592_p2 == 1'd1) & (tmp_140_fu_555_p2 == 1'd1) & (tmp_147_fu_603_p2 == 1'd0) & (tmp_s_fu_546_p2 == 1'd0) & (tmp_fu_534_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_147_fu_603_p2 == 1'd1) & (tmp_145_fu_592_p2 == 1'd1) & (tmp_140_fu_555_p2 == 1'd1) & (tmp_149_fu_623_p2 == 1'd0) & (tmp_s_fu_546_p2 == 1'd0) & (tmp_fu_534_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_149_fu_623_p2 == 1'd1) & (tmp_147_fu_603_p2 == 1'd1) & (tmp_145_fu_592_p2 == 1'd1) & (tmp_140_fu_555_p2 == 1'd1) & (tmp_s_fu_546_p2 == 1'd0) & (tmp_fu_534_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | (~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        k_x_1_fu_92 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_145_fu_592_p2 == 1'd1) & (tmp_140_fu_555_p2 == 1'd1) & (tmp_147_fu_603_p2 == 1'd0) & (tmp_s_fu_546_p2 == 1'd0) & (tmp_fu_534_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_y_1_fu_84 <= k_y_2_fu_574_p2;
    end else if ((((tmp_147_fu_603_p2 == 1'd1) & (tmp_145_fu_592_p2 == 1'd1) & (tmp_140_fu_555_p2 == 1'd1) & (tmp_s_fu_546_p2 == 1'd0) & (tmp_fu_534_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | (~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        k_y_1_fu_84 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_147_fu_603_p2 == 1'd1) & (tmp_145_fu_592_p2 == 1'd1) & (tmp_140_fu_555_p2 == 1'd1) & (tmp_149_fu_623_p2 == 1'd0) & (tmp_s_fu_546_p2 == 1'd0) & (tmp_fu_534_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ofm_x_1_fu_80 <= ofm_x_2_fu_617_p2;
    end else if ((((tmp_149_fu_623_p2 == 1'd1) & (tmp_147_fu_603_p2 == 1'd1) & (tmp_145_fu_592_p2 == 1'd1) & (tmp_140_fu_555_p2 == 1'd1) & (tmp_s_fu_546_p2 == 1'd0) & (tmp_fu_534_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | (~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        ofm_x_1_fu_80 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_140_reg_888 == 1'd1) & (tmp_149_reg_910 == 1'd1) & (tmp_147_reg_906 == 1'd1) & (tmp_145_reg_902 == 1'd1) & (tmp_s_reg_884 == 1'd0) & (tmp_reg_875 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ofm_y_1_fu_76 <= p_ofm_y_2_fu_693_p3;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ofm_y_1_fu_76 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((((or_cond_reg_925 == 1'd1) & (grp_fu_484_p2 == 1'd1) & (tmp_s_reg_884 == 1'd0) & (tmp_reg_875 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((grp_fu_484_p2 == 1'd1) & (tmp_s_reg_884 == 1'd1) & (tmp_reg_875 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        read_block_1_fu_96 <= grp_fu_443_p2;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        read_block_1_fu_96 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_fu_546_p2 == 1'd0) & (tmp_fu_534_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        counter_internal_blo_19_reg_929 <= counter_internal_blo_19_fu_673_p2;
        or_cond_reg_925 <= or_cond_fu_664_p2;
        tmp_140_reg_888 <= tmp_140_fu_555_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_140_fu_555_p2 == 1'd1) & (tmp_s_fu_546_p2 == 1'd0) & (tmp_fu_534_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        current_line_in_bloc_reg_897 <= current_line_in_bloc_fu_580_p2;
        tmp_1382_reg_892 <= tmp_1382_fu_570_p1;
        tmp_145_reg_902 <= tmp_145_fu_592_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        i_s_reg_879 <= i_s_fu_540_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_140_reg_888 == 1'd1) & (tmp_s_reg_884 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inputBuf_0_0_V_loa_reg_977 <= inputBuf_0_0_V_q0;
        inputBuf_1_0_V_loa_reg_982 <= inputBuf_1_0_V_q0;
        inputBuf_2_0_V_loa_reg_987 <= inputBuf_2_0_V_q0;
        inputBuf_3_0_V_loa_reg_992 <= inputBuf_3_0_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_reg_925 == 1'd1) & (tmp_s_reg_884 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inputBuf_0_1_V_add_12_reg_1021 <= tmp_153_fu_755_p1;
        inputBuf_1_1_V_add_12_reg_1026 <= tmp_153_fu_755_p1;
        inputBuf_2_1_V_add_12_reg_1031 <= tmp_153_fu_755_p1;
        inputBuf_3_1_V_add_12_reg_1036 <= tmp_153_fu_755_p1;
        tmp_1384_reg_1017 <= tmp_1384_fu_767_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_reg_884 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inputBuf_0_1_V_add_reg_1045 <= tmp_139_fu_771_p1;
        inputBuf_1_1_V_add_reg_1050 <= tmp_139_fu_771_p1;
        inputBuf_2_1_V_add_reg_1055 <= tmp_139_fu_771_p1;
        inputBuf_3_1_V_add_reg_1060 <= tmp_139_fu_771_p1;
        tmp_1381_reg_1041 <= tmp_1381_fu_783_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_140_reg_888_pp0_iter1_reg == 1'd1) & (tmp_s_reg_884_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        inputBuf_0_1_V_loa_reg_1065 <= inputBuf_0_1_V_q0;
        inputBuf_1_1_V_loa_reg_1070 <= inputBuf_1_1_V_q0;
        inputBuf_2_1_V_loa_reg_1075 <= inputBuf_2_1_V_q0;
        inputBuf_3_1_V_loa_reg_1080 <= inputBuf_3_1_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_149_fu_623_p2 == 1'd1) & (tmp_147_fu_603_p2 == 1'd1) & (tmp_145_fu_592_p2 == 1'd1) & (tmp_140_fu_555_p2 == 1'd1) & (tmp_s_fu_546_p2 == 1'd0) & (tmp_fu_534_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ofm_y_2_reg_914 <= ofm_y_2_fu_637_p2;
        tmp_150_reg_919 <= tmp_150_fu_643_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        or_cond_reg_925_pp0_iter1_reg <= or_cond_reg_925;
        tmp_140_reg_888_pp0_iter1_reg <= tmp_140_reg_888;
        tmp_reg_875 <= tmp_fu_534_p2;
        tmp_s_reg_884_pp0_iter1_reg <= tmp_s_reg_884;
    end
end

always @ (posedge ap_clk) begin
    if ((((tmp_s_fu_546_p2 == 1'd1) & (tmp_fu_534_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((or_cond_fu_664_p2 == 1'd1) & (tmp_s_fu_546_p2 == 1'd0) & (tmp_fu_534_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        reg_460 <= grp_fu_434_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((or_cond_reg_925 == 1'd1) & (tmp_s_reg_884 == 1'd0) & (tmp_reg_875 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((tmp_s_reg_884 == 1'd1) & (tmp_reg_875 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        reg_464 <= current_line_1_fu_104;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op168_read_state4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_s_reg_884 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_predicate_op128_read_state3 == 1'b1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_predicate_op110_read_state3 == 1'b1)))) begin
        reg_468 <= in_V_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((((or_cond_reg_925 == 1'd1) & (grp_fu_484_p2 == 1'd1) & (tmp_s_reg_884 == 1'd0) & (tmp_reg_875 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((grp_fu_484_p2 == 1'd1) & (tmp_s_reg_884 == 1'd1) & (tmp_reg_875 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        reg_480 <= grp_fu_449_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_140_reg_888 == 1'd1) & (tmp_s_reg_884 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_143_reg_971 <= tmp_143_fu_747_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_140_reg_888 == 1'd1) & (tmp_s_reg_884 == 1'd0) & (tmp_reg_875 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        tmp_144_reg_935[31 : 0] <= tmp_144_fu_679_p1[31 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_reg_884 == 1'd1) & (tmp_reg_875 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        tmp_146_reg_967 <= grp_fu_484_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_145_fu_592_p2 == 1'd1) & (tmp_140_fu_555_p2 == 1'd1) & (tmp_s_fu_546_p2 == 1'd0) & (tmp_fu_534_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_147_reg_906 <= tmp_147_fu_603_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_147_fu_603_p2 == 1'd1) & (tmp_145_fu_592_p2 == 1'd1) & (tmp_140_fu_555_p2 == 1'd1) & (tmp_s_fu_546_p2 == 1'd0) & (tmp_fu_534_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_149_reg_910 <= tmp_149_fu_623_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_reg_925 == 1'd1) & (tmp_s_reg_884 == 1'd0) & (tmp_reg_875 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        tmp_156_reg_963 <= grp_fu_484_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_534_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_s_reg_884 <= tmp_s_fu_546_p2;
    end
end

always @ (*) begin
    if ((tmp_fu_534_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (tmp_reg_875 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_i_phi_fu_393_p4 = i_s_reg_879;
    end else begin
        ap_phi_mux_i_phi_fu_393_p4 = i_reg_389;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (or_cond_reg_925 == 1'd1) & (tmp_s_reg_884 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0) & (tmp_s_reg_884 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((or_cond_reg_925 == 1'd1) & (tmp_s_reg_884 == 1'd0) & (tmp_reg_875 == 1'd0) & (1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((tmp_s_reg_884 == 1'd1) & (tmp_reg_875 == 1'd0) & (1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        in_V_V_blk_n = in_V_V_empty_n;
    end else begin
        in_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op168_read_state4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_s_reg_884 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_predicate_op128_read_state3 == 1'b1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_predicate_op110_read_state3 == 1'b1)))) begin
        in_V_V_read = 1'b1;
    end else begin
        in_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_81)) begin
        if (((tmp_s_reg_884 == 1'd1) & (tmp_1381_fu_783_p1 == 2'd0))) begin
            inputBuf_0_0_V_address1 = tmp_139_fu_771_p1;
        end else if ((1'b1 == ap_condition_550)) begin
            inputBuf_0_0_V_address1 = tmp_153_fu_755_p1;
        end else begin
            inputBuf_0_0_V_address1 = 'bx;
        end
    end else begin
        inputBuf_0_0_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        inputBuf_0_0_V_ce0 = 1'b1;
    end else begin
        inputBuf_0_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_reg_925 == 1'd1) & (tmp_s_reg_884 == 1'd0) & (tmp_1384_fu_767_p1 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_s_reg_884 == 1'd1) & (tmp_1381_fu_783_p1 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        inputBuf_0_0_V_ce1 = 1'b1;
    end else begin
        inputBuf_0_0_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_reg_925 == 1'd1) & (tmp_s_reg_884 == 1'd0) & (tmp_1384_fu_767_p1 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_s_reg_884 == 1'd1) & (tmp_1381_fu_783_p1 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        inputBuf_0_0_V_we1 = 1'b1;
    end else begin
        inputBuf_0_0_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_96)) begin
        if (((tmp_s_reg_884_pp0_iter1_reg == 1'd1) & (tmp_1381_reg_1041 == 2'd0))) begin
            inputBuf_0_1_V_address1 = inputBuf_0_1_V_add_reg_1045;
        end else if ((1'b1 == ap_condition_595)) begin
            inputBuf_0_1_V_address1 = inputBuf_0_1_V_add_12_reg_1021;
        end else begin
            inputBuf_0_1_V_address1 = 'bx;
        end
    end else begin
        inputBuf_0_1_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inputBuf_0_1_V_ce0 = 1'b1;
    end else begin
        inputBuf_0_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_reg_925_pp0_iter1_reg == 1'd1) & (tmp_s_reg_884_pp0_iter1_reg == 1'd0) & (tmp_1384_reg_1017 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((tmp_s_reg_884_pp0_iter1_reg == 1'd1) & (tmp_1381_reg_1041 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        inputBuf_0_1_V_ce1 = 1'b1;
    end else begin
        inputBuf_0_1_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_reg_925_pp0_iter1_reg == 1'd1) & (tmp_s_reg_884_pp0_iter1_reg == 1'd0) & (tmp_1384_reg_1017 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((tmp_s_reg_884_pp0_iter1_reg == 1'd1) & (tmp_1381_reg_1041 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        inputBuf_0_1_V_we1 = 1'b1;
    end else begin
        inputBuf_0_1_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_81)) begin
        if (((tmp_s_reg_884 == 1'd1) & (tmp_1381_fu_783_p1 == 2'd1))) begin
            inputBuf_1_0_V_address1 = tmp_139_fu_771_p1;
        end else if ((1'b1 == ap_condition_561)) begin
            inputBuf_1_0_V_address1 = tmp_153_fu_755_p1;
        end else begin
            inputBuf_1_0_V_address1 = 'bx;
        end
    end else begin
        inputBuf_1_0_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        inputBuf_1_0_V_ce0 = 1'b1;
    end else begin
        inputBuf_1_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_reg_925 == 1'd1) & (tmp_s_reg_884 == 1'd0) & (tmp_1384_fu_767_p1 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_s_reg_884 == 1'd1) & (tmp_1381_fu_783_p1 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        inputBuf_1_0_V_ce1 = 1'b1;
    end else begin
        inputBuf_1_0_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_reg_925 == 1'd1) & (tmp_s_reg_884 == 1'd0) & (tmp_1384_fu_767_p1 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_s_reg_884 == 1'd1) & (tmp_1381_fu_783_p1 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        inputBuf_1_0_V_we1 = 1'b1;
    end else begin
        inputBuf_1_0_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_96)) begin
        if (((tmp_s_reg_884_pp0_iter1_reg == 1'd1) & (tmp_1381_reg_1041 == 2'd1))) begin
            inputBuf_1_1_V_address1 = inputBuf_1_1_V_add_reg_1050;
        end else if ((1'b1 == ap_condition_606)) begin
            inputBuf_1_1_V_address1 = inputBuf_1_1_V_add_12_reg_1026;
        end else begin
            inputBuf_1_1_V_address1 = 'bx;
        end
    end else begin
        inputBuf_1_1_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inputBuf_1_1_V_ce0 = 1'b1;
    end else begin
        inputBuf_1_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_reg_925_pp0_iter1_reg == 1'd1) & (tmp_s_reg_884_pp0_iter1_reg == 1'd0) & (tmp_1384_reg_1017 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((tmp_s_reg_884_pp0_iter1_reg == 1'd1) & (tmp_1381_reg_1041 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        inputBuf_1_1_V_ce1 = 1'b1;
    end else begin
        inputBuf_1_1_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_reg_925_pp0_iter1_reg == 1'd1) & (tmp_s_reg_884_pp0_iter1_reg == 1'd0) & (tmp_1384_reg_1017 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((tmp_s_reg_884_pp0_iter1_reg == 1'd1) & (tmp_1381_reg_1041 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        inputBuf_1_1_V_we1 = 1'b1;
    end else begin
        inputBuf_1_1_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_81)) begin
        if (((tmp_s_reg_884 == 1'd1) & (tmp_1381_fu_783_p1 == 2'd2))) begin
            inputBuf_2_0_V_address1 = tmp_139_fu_771_p1;
        end else if ((1'b1 == ap_condition_572)) begin
            inputBuf_2_0_V_address1 = tmp_153_fu_755_p1;
        end else begin
            inputBuf_2_0_V_address1 = 'bx;
        end
    end else begin
        inputBuf_2_0_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        inputBuf_2_0_V_ce0 = 1'b1;
    end else begin
        inputBuf_2_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_reg_925 == 1'd1) & (tmp_s_reg_884 == 1'd0) & (tmp_1384_fu_767_p1 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_s_reg_884 == 1'd1) & (tmp_1381_fu_783_p1 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        inputBuf_2_0_V_ce1 = 1'b1;
    end else begin
        inputBuf_2_0_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_reg_925 == 1'd1) & (tmp_s_reg_884 == 1'd0) & (tmp_1384_fu_767_p1 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_s_reg_884 == 1'd1) & (tmp_1381_fu_783_p1 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        inputBuf_2_0_V_we1 = 1'b1;
    end else begin
        inputBuf_2_0_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_96)) begin
        if (((tmp_s_reg_884_pp0_iter1_reg == 1'd1) & (tmp_1381_reg_1041 == 2'd2))) begin
            inputBuf_2_1_V_address1 = inputBuf_2_1_V_add_reg_1055;
        end else if ((1'b1 == ap_condition_616)) begin
            inputBuf_2_1_V_address1 = inputBuf_2_1_V_add_12_reg_1031;
        end else begin
            inputBuf_2_1_V_address1 = 'bx;
        end
    end else begin
        inputBuf_2_1_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inputBuf_2_1_V_ce0 = 1'b1;
    end else begin
        inputBuf_2_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_reg_925_pp0_iter1_reg == 1'd1) & (tmp_s_reg_884_pp0_iter1_reg == 1'd0) & (tmp_1384_reg_1017 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((tmp_s_reg_884_pp0_iter1_reg == 1'd1) & (tmp_1381_reg_1041 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        inputBuf_2_1_V_ce1 = 1'b1;
    end else begin
        inputBuf_2_1_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_reg_925_pp0_iter1_reg == 1'd1) & (tmp_s_reg_884_pp0_iter1_reg == 1'd0) & (tmp_1384_reg_1017 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((tmp_s_reg_884_pp0_iter1_reg == 1'd1) & (tmp_1381_reg_1041 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        inputBuf_2_1_V_we1 = 1'b1;
    end else begin
        inputBuf_2_1_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_81)) begin
        if (((tmp_s_reg_884 == 1'd1) & (tmp_1381_fu_783_p1 == 2'd3))) begin
            inputBuf_3_0_V_address1 = tmp_139_fu_771_p1;
        end else if ((1'b1 == ap_condition_583)) begin
            inputBuf_3_0_V_address1 = tmp_153_fu_755_p1;
        end else begin
            inputBuf_3_0_V_address1 = 'bx;
        end
    end else begin
        inputBuf_3_0_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        inputBuf_3_0_V_ce0 = 1'b1;
    end else begin
        inputBuf_3_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_reg_925 == 1'd1) & (tmp_s_reg_884 == 1'd0) & (tmp_1384_fu_767_p1 == 2'd3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_s_reg_884 == 1'd1) & (tmp_1381_fu_783_p1 == 2'd3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        inputBuf_3_0_V_ce1 = 1'b1;
    end else begin
        inputBuf_3_0_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_reg_925 == 1'd1) & (tmp_s_reg_884 == 1'd0) & (tmp_1384_fu_767_p1 == 2'd3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_s_reg_884 == 1'd1) & (tmp_1381_fu_783_p1 == 2'd3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        inputBuf_3_0_V_we1 = 1'b1;
    end else begin
        inputBuf_3_0_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_96)) begin
        if (((tmp_s_reg_884_pp0_iter1_reg == 1'd1) & (tmp_1381_reg_1041 == 2'd3))) begin
            inputBuf_3_1_V_address1 = inputBuf_3_1_V_add_reg_1060;
        end else if ((1'b1 == ap_condition_626)) begin
            inputBuf_3_1_V_address1 = inputBuf_3_1_V_add_12_reg_1036;
        end else begin
            inputBuf_3_1_V_address1 = 'bx;
        end
    end else begin
        inputBuf_3_1_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inputBuf_3_1_V_ce0 = 1'b1;
    end else begin
        inputBuf_3_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_reg_925_pp0_iter1_reg == 1'd1) & (tmp_s_reg_884_pp0_iter1_reg == 1'd0) & (tmp_1384_reg_1017 == 2'd3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((tmp_s_reg_884_pp0_iter1_reg == 1'd1) & (tmp_1381_reg_1041 == 2'd3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        inputBuf_3_1_V_ce1 = 1'b1;
    end else begin
        inputBuf_3_1_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_reg_925_pp0_iter1_reg == 1'd1) & (tmp_s_reg_884_pp0_iter1_reg == 1'd0) & (tmp_1384_reg_1017 == 2'd3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((tmp_s_reg_884_pp0_iter1_reg == 1'd1) & (tmp_1381_reg_1041 == 2'd3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        inputBuf_3_1_V_we1 = 1'b1;
    end else begin
        inputBuf_3_1_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (tmp_140_reg_888_pp0_iter1_reg == 1'd1) & (tmp_s_reg_884_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_140_reg_888_pp0_iter1_reg == 1'd1) & (tmp_s_reg_884_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        out_V_V_blk_n = out_V_V_full_n;
    end else begin
        out_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op228_write_state6 == 1'b1))) begin
        out_V_V_din = tmp_V_51_fu_797_p6;
    end else if (((1'b0 == ap_block_pp0_stage1_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_predicate_op206_write_state5 == 1'b1))) begin
        out_V_V_din = tmp_V_50_fu_787_p6;
    end else begin
        out_V_V_din = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op228_write_state6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_predicate_op206_write_state5 == 1'b1)))) begin
        out_V_V_write = 1'b1;
    end else begin
        out_V_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b0) & (tmp_fu_534_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1)) & ~((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if ((((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b0) & (tmp_fu_534_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_pp0 = (((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone)) | ((ap_ST_fsm_pp0_stage1 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage1_subdone)));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (((tmp_s_reg_884 == 1'd1) & (in_V_V_empty_n == 1'b0)) | ((in_V_V_empty_n == 1'b0) & (ap_predicate_op168_read_state4 == 1'b1)))) | ((out_V_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op228_write_state6 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (((tmp_s_reg_884 == 1'd1) & (in_V_V_empty_n == 1'b0)) | ((in_V_V_empty_n == 1'b0) & (ap_predicate_op168_read_state4 == 1'b1)))) | ((out_V_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op228_write_state6 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (((tmp_s_reg_884 == 1'd1) & (in_V_V_empty_n == 1'b0)) | ((in_V_V_empty_n == 1'b0) & (ap_predicate_op168_read_state4 == 1'b1)))) | ((out_V_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op228_write_state6 == 1'b1)));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_01001 = (((out_V_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (ap_predicate_op206_write_state5 == 1'b1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (((in_V_V_empty_n == 1'b0) & (ap_predicate_op128_read_state3 == 1'b1)) | ((in_V_V_empty_n == 1'b0) & (ap_predicate_op110_read_state3 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((out_V_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (ap_predicate_op206_write_state5 == 1'b1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (((in_V_V_empty_n == 1'b0) & (ap_predicate_op128_read_state3 == 1'b1)) | ((in_V_V_empty_n == 1'b0) & (ap_predicate_op110_read_state3 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((out_V_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (ap_predicate_op206_write_state5 == 1'b1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (((in_V_V_empty_n == 1'b0) & (ap_predicate_op128_read_state3 == 1'b1)) | ((in_V_V_empty_n == 1'b0) & (ap_predicate_op110_read_state3 == 1'b1)))));
end

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage1_iter0 = (((in_V_V_empty_n == 1'b0) & (ap_predicate_op128_read_state3 == 1'b1)) | ((in_V_V_empty_n == 1'b0) & (ap_predicate_op110_read_state3 == 1'b1)));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter1 = (((tmp_s_reg_884 == 1'd1) & (in_V_V_empty_n == 1'b0)) | ((in_V_V_empty_n == 1'b0) & (ap_predicate_op168_read_state4 == 1'b1)));
end

always @ (*) begin
    ap_block_state5_pp0_stage1_iter1 = ((out_V_V_full_n == 1'b0) & (ap_predicate_op206_write_state5 == 1'b1));
end

always @ (*) begin
    ap_block_state6_pp0_stage0_iter2 = ((out_V_V_full_n == 1'b0) & (ap_predicate_op228_write_state6 == 1'b1));
end

always @ (*) begin
    ap_condition_550 = ((or_cond_reg_925 == 1'd1) & (tmp_s_reg_884 == 1'd0) & (tmp_1384_fu_767_p1 == 2'd0));
end

always @ (*) begin
    ap_condition_561 = ((or_cond_reg_925 == 1'd1) & (tmp_s_reg_884 == 1'd0) & (tmp_1384_fu_767_p1 == 2'd1));
end

always @ (*) begin
    ap_condition_572 = ((or_cond_reg_925 == 1'd1) & (tmp_s_reg_884 == 1'd0) & (tmp_1384_fu_767_p1 == 2'd2));
end

always @ (*) begin
    ap_condition_583 = ((or_cond_reg_925 == 1'd1) & (tmp_s_reg_884 == 1'd0) & (tmp_1384_fu_767_p1 == 2'd3));
end

always @ (*) begin
    ap_condition_595 = ((or_cond_reg_925_pp0_iter1_reg == 1'd1) & (tmp_s_reg_884_pp0_iter1_reg == 1'd0) & (tmp_1384_reg_1017 == 2'd0));
end

always @ (*) begin
    ap_condition_606 = ((or_cond_reg_925_pp0_iter1_reg == 1'd1) & (tmp_s_reg_884_pp0_iter1_reg == 1'd0) & (tmp_1384_reg_1017 == 2'd1));
end

always @ (*) begin
    ap_condition_616 = ((or_cond_reg_925_pp0_iter1_reg == 1'd1) & (tmp_s_reg_884_pp0_iter1_reg == 1'd0) & (tmp_1384_reg_1017 == 2'd2));
end

always @ (*) begin
    ap_condition_626 = ((or_cond_reg_925_pp0_iter1_reg == 1'd1) & (tmp_s_reg_884_pp0_iter1_reg == 1'd0) & (tmp_1384_reg_1017 == 2'd3));
end

always @ (*) begin
    ap_condition_81 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_96 = ((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1));
end

always @ (*) begin
    ap_enable_operation_100 = (ap_predicate_op100_load_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_102 = (ap_predicate_op102_load_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_147 = (ap_predicate_op147_load_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_148 = (ap_predicate_op148_load_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_149 = (ap_predicate_op149_load_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_150 = (ap_predicate_op150_load_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_152 = (ap_predicate_op152_load_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_154 = (ap_predicate_op154_load_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_156 = (ap_predicate_op156_load_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_158 = (ap_predicate_op158_load_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_174 = (ap_predicate_op174_store_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_175 = (ap_predicate_op175_store_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_176 = (ap_predicate_op176_store_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_177 = (ap_predicate_op177_store_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_197 = (ap_predicate_op197_store_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_198 = (ap_predicate_op198_store_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_199 = (ap_predicate_op199_store_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_200 = (ap_predicate_op200_store_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_207 = (ap_predicate_op207_load_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_208 = (ap_predicate_op208_load_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_209 = (ap_predicate_op209_load_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_210 = (ap_predicate_op210_load_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_211 = (ap_predicate_op211_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_213 = (ap_predicate_op213_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_215 = (ap_predicate_op215_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_217 = (ap_predicate_op217_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_219 = (ap_predicate_op219_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_221 = (ap_predicate_op221_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_223 = (ap_predicate_op223_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_225 = (ap_predicate_op225_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_96 = (ap_predicate_op96_load_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_98 = (ap_predicate_op98_load_state3 == 1'b1);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_enable_state3_pp0_iter0_stage1 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1));
end

always @ (*) begin
    ap_enable_state4_pp0_iter1_stage0 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state5_pp0_iter1_stage1 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1));
end

always @ (*) begin
    ap_predicate_op100_load_state3 = ((tmp_140_reg_888 == 1'd1) & (tmp_s_reg_884 == 1'd0) & (tmp_reg_875 == 1'd0));
end

always @ (*) begin
    ap_predicate_op102_load_state3 = ((tmp_140_reg_888 == 1'd1) & (tmp_s_reg_884 == 1'd0) & (tmp_reg_875 == 1'd0));
end

always @ (*) begin
    ap_predicate_op110_read_state3 = ((or_cond_reg_925 == 1'd1) & (tmp_s_reg_884 == 1'd0) & (tmp_reg_875 == 1'd0));
end

always @ (*) begin
    ap_predicate_op128_read_state3 = ((tmp_s_reg_884 == 1'd1) & (tmp_reg_875 == 1'd0));
end

always @ (*) begin
    ap_predicate_op147_load_state4 = ((tmp_140_reg_888 == 1'd1) & (tmp_s_reg_884 == 1'd0));
end

always @ (*) begin
    ap_predicate_op148_load_state4 = ((tmp_140_reg_888 == 1'd1) & (tmp_s_reg_884 == 1'd0));
end

always @ (*) begin
    ap_predicate_op149_load_state4 = ((tmp_140_reg_888 == 1'd1) & (tmp_s_reg_884 == 1'd0));
end

always @ (*) begin
    ap_predicate_op150_load_state4 = ((tmp_140_reg_888 == 1'd1) & (tmp_s_reg_884 == 1'd0));
end

always @ (*) begin
    ap_predicate_op152_load_state4 = ((tmp_140_reg_888 == 1'd1) & (tmp_s_reg_884 == 1'd0));
end

always @ (*) begin
    ap_predicate_op154_load_state4 = ((tmp_140_reg_888 == 1'd1) & (tmp_s_reg_884 == 1'd0));
end

always @ (*) begin
    ap_predicate_op156_load_state4 = ((tmp_140_reg_888 == 1'd1) & (tmp_s_reg_884 == 1'd0));
end

always @ (*) begin
    ap_predicate_op158_load_state4 = ((tmp_140_reg_888 == 1'd1) & (tmp_s_reg_884 == 1'd0));
end

always @ (*) begin
    ap_predicate_op168_read_state4 = ((or_cond_reg_925 == 1'd1) & (tmp_s_reg_884 == 1'd0));
end

always @ (*) begin
    ap_predicate_op174_store_state4 = ((or_cond_reg_925 == 1'd1) & (tmp_s_reg_884 == 1'd0) & (tmp_1384_fu_767_p1 == 2'd2));
end

always @ (*) begin
    ap_predicate_op175_store_state4 = ((or_cond_reg_925 == 1'd1) & (tmp_s_reg_884 == 1'd0) & (tmp_1384_fu_767_p1 == 2'd1));
end

always @ (*) begin
    ap_predicate_op176_store_state4 = ((or_cond_reg_925 == 1'd1) & (tmp_s_reg_884 == 1'd0) & (tmp_1384_fu_767_p1 == 2'd0));
end

always @ (*) begin
    ap_predicate_op177_store_state4 = ((or_cond_reg_925 == 1'd1) & (tmp_s_reg_884 == 1'd0) & (tmp_1384_fu_767_p1 == 2'd3));
end

always @ (*) begin
    ap_predicate_op197_store_state4 = ((tmp_s_reg_884 == 1'd1) & (tmp_1381_fu_783_p1 == 2'd2));
end

always @ (*) begin
    ap_predicate_op198_store_state4 = ((tmp_s_reg_884 == 1'd1) & (tmp_1381_fu_783_p1 == 2'd1));
end

always @ (*) begin
    ap_predicate_op199_store_state4 = ((tmp_s_reg_884 == 1'd1) & (tmp_1381_fu_783_p1 == 2'd0));
end

always @ (*) begin
    ap_predicate_op200_store_state4 = ((tmp_s_reg_884 == 1'd1) & (tmp_1381_fu_783_p1 == 2'd3));
end

always @ (*) begin
    ap_predicate_op206_write_state5 = ((tmp_140_reg_888_pp0_iter1_reg == 1'd1) & (tmp_s_reg_884_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op207_load_state5 = ((tmp_140_reg_888_pp0_iter1_reg == 1'd1) & (tmp_s_reg_884_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op208_load_state5 = ((tmp_140_reg_888_pp0_iter1_reg == 1'd1) & (tmp_s_reg_884_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op209_load_state5 = ((tmp_140_reg_888_pp0_iter1_reg == 1'd1) & (tmp_s_reg_884_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op210_load_state5 = ((tmp_140_reg_888_pp0_iter1_reg == 1'd1) & (tmp_s_reg_884_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op211_store_state5 = ((or_cond_reg_925_pp0_iter1_reg == 1'd1) & (tmp_s_reg_884_pp0_iter1_reg == 1'd0) & (tmp_1384_reg_1017 == 2'd2));
end

always @ (*) begin
    ap_predicate_op213_store_state5 = ((or_cond_reg_925_pp0_iter1_reg == 1'd1) & (tmp_s_reg_884_pp0_iter1_reg == 1'd0) & (tmp_1384_reg_1017 == 2'd1));
end

always @ (*) begin
    ap_predicate_op215_store_state5 = ((or_cond_reg_925_pp0_iter1_reg == 1'd1) & (tmp_s_reg_884_pp0_iter1_reg == 1'd0) & (tmp_1384_reg_1017 == 2'd0));
end

always @ (*) begin
    ap_predicate_op217_store_state5 = ((or_cond_reg_925_pp0_iter1_reg == 1'd1) & (tmp_s_reg_884_pp0_iter1_reg == 1'd0) & (tmp_1384_reg_1017 == 2'd3));
end

always @ (*) begin
    ap_predicate_op219_store_state5 = ((tmp_s_reg_884_pp0_iter1_reg == 1'd1) & (tmp_1381_reg_1041 == 2'd2));
end

always @ (*) begin
    ap_predicate_op221_store_state5 = ((tmp_s_reg_884_pp0_iter1_reg == 1'd1) & (tmp_1381_reg_1041 == 2'd1));
end

always @ (*) begin
    ap_predicate_op223_store_state5 = ((tmp_s_reg_884_pp0_iter1_reg == 1'd1) & (tmp_1381_reg_1041 == 2'd0));
end

always @ (*) begin
    ap_predicate_op225_store_state5 = ((tmp_s_reg_884_pp0_iter1_reg == 1'd1) & (tmp_1381_reg_1041 == 2'd3));
end

always @ (*) begin
    ap_predicate_op228_write_state6 = ((tmp_140_reg_888_pp0_iter1_reg == 1'd1) & (tmp_s_reg_884_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op96_load_state3 = ((tmp_140_reg_888 == 1'd1) & (tmp_s_reg_884 == 1'd0) & (tmp_reg_875 == 1'd0));
end

always @ (*) begin
    ap_predicate_op98_load_state3 = ((tmp_140_reg_888 == 1'd1) & (tmp_s_reg_884 == 1'd0) & (tmp_reg_875 == 1'd0));
end

assign ap_ready = internal_ap_ready;

assign counter_internal_blo_19_fu_673_p2 = (counter_internal_blo_fu_108 + 32'd1);

assign current_line_in_bloc_fu_580_p2 = (ofm_x_1_fu_80 + k_x_1_fu_92);

assign grp_fu_434_p2 = (current_line_1_fu_104 + 32'd1);

assign grp_fu_443_p2 = (read_block_1_fu_96 + 32'd1);

assign grp_fu_449_p2 = (current_block_write_s_fu_100 + 32'd1);

assign grp_fu_484_p2 = ((reg_460 == 32'd30) ? 1'b1 : 1'b0);

assign grp_fu_495_p2 = ((reg_480 == 32'd4) ? 1'b1 : 1'b0);

assign grp_fu_501_p3 = ((grp_fu_495_p2[0:0] === 1'b1) ? 32'd0 : reg_480);

assign i_s_fu_540_p2 = (ap_phi_mux_i_phi_fu_393_p4 + 13'd1);

assign inp_1_fu_726_p2 = (inp_s_fu_88 + 32'd1);

assign inputBuf_0_0_V_address0 = tmp_144_fu_679_p1;

assign inputBuf_0_1_V_address0 = tmp_144_reg_935;

assign inputBuf_1_0_V_address0 = tmp_144_fu_679_p1;

assign inputBuf_1_1_V_address0 = tmp_144_reg_935;

assign inputBuf_2_0_V_address0 = tmp_144_fu_679_p1;

assign inputBuf_2_1_V_address0 = tmp_144_reg_935;

assign inputBuf_3_0_V_address0 = tmp_144_fu_679_p1;

assign inputBuf_3_1_V_address0 = tmp_144_reg_935;

assign k_x_2_fu_586_p2 = (32'd1 + k_x_1_fu_92);

assign k_y_2_fu_574_p2 = (32'd1 + k_y_1_fu_84);

assign ofm_x_2_fu_617_p2 = (ofm_x_1_fu_80 + 32'd1);

assign ofm_y_2_fu_637_p2 = (ofm_y_1_fu_76 + 32'd1);

assign or_cond_fu_664_p2 = (tmp_152_fu_658_p2 & tmp_151_fu_652_p2);

assign p_inp_s_fu_686_p3 = ((tmp_150_reg_919[0:0] === 1'b1) ? 32'd0 : inp_s_fu_88);

assign p_ofm_y_2_fu_693_p3 = ((tmp_150_reg_919[0:0] === 1'b1) ? 32'd0 : ofm_y_2_reg_914);

assign p_s_fu_714_p3 = ((tmp_159_fu_709_p2[0:0] === 1'b1) ? 32'd0 : counter_internal_blo_19_reg_929);

assign start_out = real_start;

assign tmp1_fu_741_p2 = (2'd1 + tmp_1383_fu_737_p1);

assign tmp_1381_fu_783_p1 = current_block_write_s_fu_100[1:0];

assign tmp_1382_fu_570_p1 = k_y_1_fu_84[1:0];

assign tmp_1383_fu_737_p1 = current_block_write_s_fu_100[1:0];

assign tmp_1384_fu_767_p1 = current_block_write_s_fu_100[1:0];

assign tmp_139_fu_771_p1 = reg_464;

assign tmp_140_fu_555_p2 = ((counter_internal_blo_fu_108 < 32'd251) ? 1'b1 : 1'b0);

assign tmp_143_fu_747_p2 = (tmp1_fu_741_p2 + tmp_1382_reg_892);

assign tmp_144_fu_679_p1 = current_line_in_bloc_reg_897;

assign tmp_145_fu_592_p2 = ((k_x_2_fu_586_p2 == 32'd3) ? 1'b1 : 1'b0);

assign tmp_147_fu_603_p2 = ((k_y_2_fu_574_p2 == 32'd3) ? 1'b1 : 1'b0);

assign tmp_149_fu_623_p2 = ((ofm_x_2_fu_617_p2 == 32'd28) ? 1'b1 : 1'b0);

assign tmp_150_fu_643_p2 = ((ofm_y_2_fu_637_p2 == 32'd28) ? 1'b1 : 1'b0);

assign tmp_151_fu_652_p2 = ((counter_internal_blo_fu_108 < 32'd29) ? 1'b1 : 1'b0);

assign tmp_152_fu_658_p2 = ((read_block_1_fu_96 < 32'd30) ? 1'b1 : 1'b0);

assign tmp_153_fu_755_p1 = reg_464;

assign tmp_159_fu_709_p2 = ((counter_internal_blo_19_reg_929 == 32'd251) ? 1'b1 : 1'b0);

assign tmp_fu_534_p2 = ((ap_phi_mux_i_phi_fu_393_p4 == 13'd7146) ? 1'b1 : 1'b0);

assign tmp_s_fu_546_p2 = ((inp_s_fu_88 < 32'd90) ? 1'b1 : 1'b0);

always @ (posedge ap_clk) begin
    tmp_144_reg_935[63:32] <= 32'b00000000000000000000000000000000;
end

endmodule //StreamingConvolution
